import:
- base.system.config_key_ctl:config_key_ctl.module
- base.system.config_value_ctl:config_value_ctl.module
- builtins:mosaic.service
- builtins:web.service
- legacy_type.builtin:attribute
- legacy_type.builtin:python_module
- legacy_type.cfg_item:typed_cfg_item
- legacy_type.system:actor_template
- legacy_type.system:data_key_ctl
- legacy_type.system:data_value_ctl
- legacy_type.system:dict_config_ctl
- legacy_type.system:flat_list_config_ctl
- legacy_type.system:item_list_config
- legacy_type.system:service_config
- legacy_type.system:system_config

definitions:

  config_ctl.module:
    type: legacy_type.builtin:python_module
    value:
      module_name: config_ctl
      file_name: config_ctl.dyn.py
      import_list:
        htypes.system.dict_config_ctl: legacy_type.system:dict_config_ctl
        htypes.system.flat_list_config_ctl: legacy_type.system:flat_list_config_ctl
        htypes.system.item_list_config: legacy_type.system:item_list_config
        htypes.system.service_config: legacy_type.system:service_config
        htypes.system.system_config: legacy_type.system:system_config
        services.mosaic: builtins:mosaic.service
        services.web: builtins:web.service
        code.config_key_ctl: base.system.config_key_ctl:config_key_ctl.module
        code.config_value_ctl: base.system.config_value_ctl:config_value_ctl.module

  FlatListConfigCtl:
    type: legacy_type.builtin:attribute
    value:
      object: config_ctl.module
      attr_name: FlatListConfigCtl

  FlatListConfigCtl.from_piece:
    type: legacy_type.builtin:attribute
    value:
      object: FlatListConfigCtl
      attr_name: from_piece

  FlatListConfigCtl.from_piece.actor-template:
    type: legacy_type.system:actor_template
    value:
      function: FlatListConfigCtl.from_piece
      service_params:
      - cfg_item_creg
      - cfg_value_creg

  config_ctl_creg-system-flat_list_config_ctl.actor-cfg-item:
    type: legacy_type.cfg_item:typed_cfg_item
    value:
      t: legacy_type.system:flat_list_config_ctl
      value: FlatListConfigCtl.from_piece.actor-template

  data_service_config.ctl:
    type: legacy_type.system:dict_config_ctl
    value:
      key_ctl: data_key.ctl
      value_ctl: data_value.ctl

  data_key.ctl:
    type: legacy_type.system:data_key_ctl
    value: {}

  data_value.ctl:
    type: legacy_type.system:data_value_ctl
    value: {}
