import:
- base.system.config_ctl:config_ctl.module
- base.system.config_struct_ctl:config_struct_ctl.module
- builtins:mosaic.service
- legacy_type.builtin:attribute
- legacy_type.builtin:python_module
- legacy_type.cfg_item:typed_cfg_item
- legacy_type.list_config_ctl:dict_list_config_ctl
- legacy_type.system:actor_template

definitions:

  list_config_ctl.module:
    type: legacy_type.builtin:python_module
    value:
      module_name: list_config_ctl
      file_name: list_config_ctl.dyn.py
      import_list:
        htypes.list_config_ctl.dict_list_config_ctl: legacy_type.list_config_ctl:dict_list_config_ctl
        services.mosaic: builtins:mosaic.service
        code.config_ctl: base.system.config_ctl:config_ctl.module
        code.config_struct_ctl: base.system.config_struct_ctl:config_struct_ctl.module

  DictListConfigCtl:
    type: legacy_type.builtin:attribute
    value:
      object: list_config_ctl.module
      attr_name: DictListConfigCtl

  DictListConfigCtl.from_piece:
    type: legacy_type.builtin:attribute
    value:
      object: DictListConfigCtl
      attr_name: from_piece

  DictListConfigCtl.from_piece.actor-template:
    type: legacy_type.system:actor_template
    value:
      function: DictListConfigCtl.from_piece
      service_params:
      - config_key_ctl_creg
      - config_value_ctl_creg
      - cfg_item_creg
      - cfg_value_creg

  config_ctl_creg-list_config_ctl-dict_list_config_ctl.actor-cfg-item:
    type: legacy_type.cfg_item:typed_cfg_item
    value:
      t: legacy_type.list_config_ctl:dict_list_config_ctl
      value: DictListConfigCtl.from_piece.actor-template

  dict_list_config_ctl:
    type: legacy_type.list_config_ctl:dict_list_config_ctl
    value: {}
