import:
- legacy_type.builtin:int
- legacy_type.builtin:string
- legacy_type.data_service:config_item
- legacy_type.int_adapter:int_adapter
- legacy_type.str_adapter:static_str_adapter
- legacy_type.system:item_list_config
- legacy_type.system:system_config
- legacy_type.text:edit_view
- legacy_type.ui:model_layout_k

definitions:

  config:
    type: legacy_type.system:system_config
    value:
      services:
        model_layout_reg: model_layout_reg.config

  model_layout_reg.config:
    type: legacy_type.system:item_list_config
    value:
      items:
      - config_item-int.layout-item
      - config_item-string.layout-item

  config_item-int.layout-item:
    type: legacy_type.data_service:config_item
    value:
      key: model_layout_k-int
      value: edit_view-int.layout

  model_layout_k-int:
    type: legacy_type.ui:model_layout_k
    value:
      model_t: legacy_type.builtin:int

  edit_view-int.layout:
    type: legacy_type.text:edit_view
    value:
      adapter: static_int_adapter

  static_int_adapter:
    type: legacy_type.int_adapter:int_adapter
    value: {}

  config_item-string.layout-item:
    type: legacy_type.data_service:config_item
    value:
      key: model_layout_k-string
      value: edit_view-string.layout

  model_layout_k-string:
    type: legacy_type.ui:model_layout_k
    value:
      model_t: legacy_type.builtin:string

  edit_view-string.layout:
    type: legacy_type.text:edit_view
    value:
      adapter: static_str_adapter

  static_str_adapter:
    type: legacy_type.str_adapter:static_str_adapter
    value: {}
