import:
- legacy_type.builtin:attribute
- legacy_type.builtin:python_module
- legacy_type.marker:marker_template
- rc.fixture_ctr:fixture_ctr.module

definitions:

  config_fixture_marker.module:
    type: legacy_type.builtin:python_module
    value:
      module_name: config_fixture_marker
      file_name: config_fixture_marker.dyn.py
      import_list:
        code.fixture_ctr: rc.fixture_ctr:fixture_ctr.module

  config_fixture_marker:
    type: legacy_type.builtin:attribute
    value:
      object: config_fixture_marker.module
      attr_name: config_fixture_marker

  config_fixture.marker-template:
    type: legacy_type.marker:marker_template
    value:
      name: config_fixture
      function: config_fixture_marker
      service_params:
      - ctr_collector
