import:
- base.mark:mark.module
- base.system.config_ctl:config_ctl.module
- legacy_type.builtin:attribute
- legacy_type.builtin:python_module
- legacy_type.cfg_item:typed_cfg_item
- legacy_type.record_config:config_ctl
- legacy_type.system:actor_template

definitions:

  record_config.module:
    type: legacy_type.builtin:python_module
    value:
      module_name: record_config
      file_name: record_config.dyn.py
      import_list:
        code.config_ctl: base.system.config_ctl:config_ctl.module
        code.mark: base.mark:mark.module
        htypes.record_config.config_ctl: legacy_type.record_config:config_ctl

  RecordConfigCtl:
    type: legacy_type.builtin:attribute
    value:
      object: record_config.module
      attr_name: RecordConfigCtl

  RecordConfigCtl.from_piece:
    type: legacy_type.builtin:attribute
    value:
      object: RecordConfigCtl
      attr_name: from_piece

  RecordConfigCtl.from_piece.actor-template:
    type: legacy_type.system:actor_template
    value:
      function: RecordConfigCtl.from_piece
      service_params: []

  config_ctl_creg-record_config-config_ctl.actor-cfg-item:
    type: legacy_type.cfg_item:typed_cfg_item
    value:
      t: legacy_type.record_config:config_ctl
      value: RecordConfigCtl.from_piece.actor-template
